### ISSUE TITLE
Getting stuck

### ISSUE THREAD

**Issue by cameronjroe** [whymarrh/metalsmith-html-minifier#12]
I'm running the plugin over about 100+ html pages. Is there a way to view the progress? It seems to just get stuck when I start a build. Any thoughts?

**Comment by whymarrh** [comment]
Hmm, there isn't anything built into the plugin that outputs progress. Version 2 has the ability to pass a pattern to the plugin, trying that with a subdirectory and working back up to the full source tree as a test might help narrow things down.

**Comment by cameronjroe** [comment]
Tried that, didn't work. Any other ideas?

**Comment by whymarrh** [comment]
I'm not sure. I don't have much to go on here. How many is 100+? I guess you could try modifying the plugin to print its progress (by adding a line [here](https://github.com/whymarrh/metalsmith-html-minifier/blob/v1.1.0/lib/index.js#L24) to log the value of `file`). You should be able to edit the file directly inside the `node_modules/` directory.

**Comment by whymarrh** [comment]
Did you manage to figure it out?

**Comment by cameronjroe** [comment]
No it still just stalls. I'm really confused.

**Comment by whymarrh** [comment]
Did you try logging the value of `file` as noted above? What did that show?

**Comment by cameronjroe** [comment]
Looks like I'm getting a parse error:

```
[17:09:32] 'dist' errored after 6.18 min
[17:09:32] Error: Parse Error: <meta property="og:title" content="We're a "Great Place to Work"">
```

**Comment by whymarrh** [comment]
Well mystery solved!

Are you handling the error in the [`build`](https://github.com/metalsmith/metalsmith/tree/faba31df3c95e4b37d072f8948d580e1df0b36af#buildfn) callback? Errors *should* get propagated to that.

**Comment by cameronjroe** [comment]
Fixed it. Thanks!
