### ISSUE TITLE
Doesn't minify files below root of source folder (with default options)

### ISSUE THREAD

**Issue by ismay** [whymarrh/metalsmith-html-minifier#27]
I just saw that any files that are in a nested folder (relative to .src()) aren't minified with the default options. Fixed by setting the pattern to `"**/*.html"`, instead of `"*.html"`.

**Comment by whymarrh** [comment]
Was this working in a previous version?

**Comment by ismay** [comment]
Don’t know. I just started using it. But I saw you changed the dependency that handles the pattern matching, maybe that’s the cause?

I’m on the latest version (installed today).

**Comment by whymarrh** [comment]
Yup, that's 100% the root cause. I'll just need to double-check how it worked previously.

**Comment by whymarrh** [comment]
Thanks for bringing this up!

**Comment by ismay** [comment]
No problem, thanks for the plugin!

**Comment by whymarrh** [comment]
Hey, so this is a breaking change and I'll be publishing an update with a fix in a bit.

(Maybe not necessarily of interest to you but hopefully you find the fixed version more intuitive.)

**Comment by whymarrh** [comment]
v2.4.4 has been released with a fix. Let me know if that works for you.

### "Just for the record"

You _should_ be able to use `*.html` to minify all HTML files in your project (e.g. both `a.html` as well as `x/y/z.html`)—that's how it used to work in 2.2.0 and before.

**Comment by ismay** [comment]
@whymarrh Tried it, and now it works as expected. It minifies all html (root and nested) when used without any options. Thanks for the fix!

**Comment by whymarrh** [comment]
Cool, thanks again for bringing this up! Feel free to close this issue once you're ready.

**Comment by ismay** [comment]
> Cool, thanks again for bringing this up! Feel free to close this issue once you're ready.

Ok cool. It's fixed for me, so I'm closing this. If anyone else encounters the same problem, feel free to reopen.
