### ISSUE TITLE
html-minifier as a peer dependency?

### ISSUE THREAD

**Issue by vvo** [whymarrh/metalsmith-html-minifier#31]
Hey thanks for this project! Would you be open at making html-minifier a peer dependency instead of a direct dependency?

The benefit of making it a peer dependency is that users can upgrade html-minifier minor versions without bugging you to upgrade your own lib.

Let me know if that's OK and Ill open a PR

**Comment by whymarrh** [comment]
I'm not _against_ making it a peer dependency but I might need a bit more convincing 🤔 

I think where npm doesn't install peer dependencies by default it could be confusing to new users.

> The benefit of making it a peer dependency is that users can upgrade html-minifier minor versions without bugging you to upgrade your own lib.

I think this is already possible where npm will "[dedupe](https://docs.npmjs.com/how-npm-works/npm3-dupe)"\* nested modules. If I understand npm correctly (which is always a big _if_), taking on a hard dependency on html-minifier should cause it to be shared with this package.

\* This documentation is the best I could find from npm, but it seems kind roundabout. What I'm thinking is that if you install metalsmith-html-minifier it should 1) already give you the latest available html-minifier minor+patch versions matching the semver range depended upon here and 2) allow you to install html-minifier as a root dependency and have it adjust what minor+patch version of html-minifier is used by metalsmith-html-minifier.

**Comment by whymarrh** [comment]
The quick test I ran in writing the comment above:

```
10:38:21 ~ $ npm --version
5.5.1
10:38:25 ~ $ cd $(mktemp -d)
10:38:31 tmp.f1MPMGs8 $ npm i metalsmith-html-minifier
+ metalsmith-html-minifier@2.4.4
added 26 packages in 1.974s
10:38:40 tmp.f1MPMGs8 $ ls node_modules/
array-differ			brace-expansion			he				minimatch			relateurl
array-union			camel-case			html-minifier			multimatch			source-map
array-uniq			clean-css			lodash.defaultsdeep		ncname				uglify-js
arrify				commander			lower-case			no-case				upper-case
balanced-match			concat-map			metalsmith-html-minifier	param-case			xml-char-classes
10:38:43 tmp.f1MPMGs8 $ npm ls
/private/var/folders/y0/dy3yx4hn6bz4z_4q2kd5xfsh0000gn/T/tmp.f1MPMGs8
└─┬ metalsmith-html-minifier@2.4.4
  ├─┬ html-minifier@3.5.7
  │ ├─┬ camel-case@3.0.0
  │ │ ├─┬ no-case@2.3.2
  │ │ │ └── lower-case@1.1.4
  │ │ └── upper-case@1.1.3
  │ ├─┬ clean-css@4.1.9
  │ │ └── source-map@0.5.7
  │ ├── commander@2.12.2
  │ ├── he@1.1.1
  │ ├─┬ ncname@1.0.0
  │ │ └── xml-char-classes@1.0.0
  │ ├─┬ param-case@2.1.1
  │ │ └── no-case@2.3.2 deduped
  │ ├── relateurl@0.2.7
  │ └─┬ uglify-js@3.2.1
  │   ├── commander@2.12.2 deduped
  │   └── source-map@0.6.1 extraneous
  ├── lodash.defaultsdeep@4.6.0
  └─┬ multimatch@2.1.0
    ├── array-differ@1.0.0
    ├─┬ array-union@1.0.2
    │ └── array-uniq@1.0.3
    ├── arrify@1.0.1
    └─┬ minimatch@3.0.4
      └─┬ brace-expansion@1.1.8
        ├── balanced-match@1.0.0
        └── concat-map@0.0.1
10:38:52 tmp.f1MPMGs8 $ npm i html-minifier@3.5.6
+ html-minifier@3.5.6
added 3 packages and updated 1 package in 1.775s
10:39:50 tmp.f1MPMGs8 $ npm ls
/private/var/folders/y0/dy3yx4hn6bz4z_4q2kd5xfsh0000gn/T/tmp.f1MPMGs8
├─┬ metalsmith-html-minifier@2.4.4
│ ├─┬ html-minifier@3.5.6
│ │ ├─┬ camel-case@3.0.0
│ │ │ ├─┬ no-case@2.3.2
│ │ │ │ └── lower-case@1.1.4
│ │ │ └── upper-case@1.1.3
│ │ ├─┬ clean-css@4.1.9
│ │ │ └── source-map@0.5.7
│ │ ├── commander@2.11.0 extraneous
│ │ ├── he@1.1.1
│ │ ├─┬ ncname@1.0.0
│ │ │ └── xml-char-classes@1.0.0
│ │ ├─┬ param-case@2.1.1
│ │ │ └── no-case@2.3.2 deduped
│ │ ├── relateurl@0.2.7
│ │ └── uglify-js@3.1.10 extraneous
│ ├── lodash.defaultsdeep@4.6.0
│ └─┬ multimatch@2.1.0
│   ├── array-differ@1.0.0
│   ├─┬ array-union@1.0.2
│   │ └── array-uniq@1.0.3
│   ├── arrify@1.0.1
│   └─┬ minimatch@3.0.4
│     └─┬ brace-expansion@1.1.8
│       ├── balanced-match@1.0.0
│       └── concat-map@0.0.1
└─┬ uglify-js@3.2.1
  ├── commander@2.12.2
  └── source-map@0.6.1 extraneous
```

Note that the install of metalsmith-html-minifier brought in `html-minifier@3.5.7`:

```
└─┬ metalsmith-html-minifier@2.4.4
  ├─┬ html-minifier@3.5.7
```

And taking on a root dependency of `html-minifier@3.5.6` changed the version used:

```
├─┬ metalsmith-html-minifier@2.4.4
│ ├─┬ html-minifier@3.5.6
```

**Comment by whymarrh** [comment]
@vvo I've added this to the v3 milestone as that's where it'd go if it was added but I'm on the fence—what do you think about my comments above?

**Comment by vvo** [comment]
I would say if your README is done in a way that says:

```sh
npm install metalsmith-html-minifier html-minifier
```

Then you are fine and good to go. This is also what ms-webpack does: https://github.com/10xjs/ms-webpack/blob/master/package.json#L47

I would not rely on any side-effect of npm/yarn for this. If you are making a module that plugs two other modules (metalsmith, html-minifier), then it's a good practice to make them peer dependencies. To inform the user: what's the supported range of metalsmith and html-minifier.

For example if you make a jQuery plugin for Google maps, you won't want to inline google maps in your plugin, nor jQuery, you would require the user to load them.

Happy to discuss further, let me know!

**Comment by whymarrh** [comment]
I could update the README to show installing both packages, that's a good idea. I think that would still be relying on npm in that npm needs to dedupe the packages—I think that's fine, since it's more a feature (on paper) and less a side-effect (because it has documentation).

I think the ms-webpack example would be more similar to having a peer dependency of `metalsmith` which, I agree completely, is a good practice. I don't think the jQuery Google Maps plugin situation is similar because the browser has a whole different set of desired behaviours and JavaScript loading/package management practices.

So, the option I see: update the documentation to note that if you want to install a custom version of `html-minifier` you can take on a direct dependency on the package to influence the version used here. This option would leave the dependencies as-is.

Thoughts? Am I missing something?

**Comment by whymarrh** [comment]
What's the use case for having a custom version used? I think I might be misunderstanding the problem that needs solving here. This package already has a loose enough dependency on `html-minifier` that you'll get the latest version (currently).

**Comment by vvo** [comment]
> So, the option I see: update the documentation to note that if you want to install a custom version of html-minifier

It works, but only because of some behaviour of npm, it might not be the case in other situations.

> What's the use case for having a custom version used?

Right now I want to use the latest version, I don't want to rely on how dependencies are flatten to get that latest version, I want to ensure Ill always have the version in my package.json being loaded and not the one you provide.

I want to do so because there will be new features and new versions in html-minifier and you don't want to bump your own package everytime it does that. I might also want to stick to a particular lower version because that's the only one working well (happens very often in various libraries, like uglifyjs).

If that's not an option no prob really, we will fork this repo and make it so I think.

**Comment by whymarrh** [comment]
> Right now I want to use the latest version, I don't want to rely on how dependencies are flatten to get that latest version

I think this might be misguided. This package already depends on a range loose enough to offer the latest minor and patch versions. There's no need to second-guess the fact that you'll always be getting the latest and greatest. This would be no different if `html-minifier` was a peer dependency.

> I might also want to stick to a particular lower version because that's the only one working well (happens very often in various libraries, like uglifyjs).

This too is already possible by taking on a dependency of `html-minifier`. (I'll admit that, yes, this is relying on npm to do the correct thing, but for this conversation, let's accept that npm works as documented.) This would be no different if `html-minifier` a peer dependency.

> I want to ensure Ill always have the version in my package.json being loaded and not the one you provide.

This is a fine goal that, yes, can only be achieved if this package doesn't directly depend on `html-minifer`, but I think that causes more problems then it solves. Let's say, for example, that this package has a peer dependency of `^3.0.0` and you want exactly `3.1.5`. You install `3.1.5`. All is well. This package now critically needs `^3.3.3`—are you going to keep using `3.1.5`? If yes, you'll need to pin a version of this package as well (which you can already do to keep the loose semver range).

I think I'm going to forgo switching to a peer dependency, sorry. I don't think it makes sense.

**Comment by vvo** [comment]
Thanks for the reasoning, we'll just create metalsmith-html-minifier2 with our need in it.
