### ISSUE TITLE
removeRedundantAttributes seems @ true by default

### ISSUE THREAD

**Issue by gaetanark** [whymarrh/metalsmith-html-minifier#5]
The actual minifier removes the ```type="text"``` attribute from input fields, setting the ```removeRedundantAttributes``` to ```false``` removes this behavior.

Apparently this values should be at false as written here : https://github.com/kangax/html-minifier/blob/b96247c0001be769e6c80541f57ed9cac9798d77/README.md#options-quick-reference

Don’t know if it’s a metalsmith-html-minifier issue or only a html-minifier issue, but there it is…

**Comment by whymarrh** [comment]
A few options are enabled by default: [options](https://github.com/whymarrh/metalsmith-html-minifier/blob/74711ab8b7987240f545df617fad2662dad9e818/README.md#options). Is that what you are referring to?

**Comment by gaetanark** [comment]
It is, thank you. I just thought the default options would be the same as it is in the *original* html-minifier.

I had an accessibility issue with ``input`` type attribute missing.(http://www.w3.org/TR/WCAG20/#minimize-error-suggestions).

**Comment by whymarrh** [comment]
That's a fair assumption though I feel that having certain options enabled is a good default. Which option caused the a11y issue? That might be something worth reporting upstream.

**Comment by gaetanark** [comment]
I agree about having some default enabled. The problem is about removeRedundantAttributes set to true as described in the issue. The upstream is set to false apparently.

**Comment by whymarrh** [comment]
I meant more that if setting that to true induces an a11y error, that might be something upstream can fix.

**Comment by gaetanark** [comment]
I agree. I open an issue there. Thank you !
